// Copyright (c) Rspscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen_deps.go; DO NOT EDIT.

package integration

import (
	// And depend on a bunch of rspscaled innards, for Go's test caching.
	// Otherwise cmd/go never sees that we depend on these packages'
	// transitive deps when we run "go install rspscaled" in a child
	// process and can cache a prior success when a dependency changes.
	_ "github.com/dblohm7/wingoes/com"
	_ "github.com/tailscale/wireguard-go/tun"
	_ "golang.org/x/sys/windows"
	_ "golang.org/x/sys/windows/svc"
	_ "golang.org/x/sys/windows/svc/eventlog"
	_ "golang.org/x/sys/windows/svc/mgr"
	_ "golang.zx2c4.com/wintun"
	_ "golang.zx2c4.com/wireguard/windows/tunnel/winipcfg"
	_ "scale.ropsoft.cloud/client/rspscale"
	_ "scale.ropsoft.cloud/cmd/rspscaled/childproc"
	_ "scale.ropsoft.cloud/control/controlclient"
	_ "scale.ropsoft.cloud/derp/derphttp"
	_ "scale.ropsoft.cloud/drive/driveimpl"
	_ "scale.ropsoft.cloud/envknob"
	_ "scale.ropsoft.cloud/health"
	_ "scale.ropsoft.cloud/hostinfo"
	_ "scale.ropsoft.cloud/ipn"
	_ "scale.ropsoft.cloud/ipn/conffile"
	_ "scale.ropsoft.cloud/ipn/ipnlocal"
	_ "scale.ropsoft.cloud/ipn/ipnserver"
	_ "scale.ropsoft.cloud/ipn/store"
	_ "scale.ropsoft.cloud/logpolicy"
	_ "scale.ropsoft.cloud/logtail"
	_ "scale.ropsoft.cloud/logtail/backoff"
	_ "scale.ropsoft.cloud/net/dns"
	_ "scale.ropsoft.cloud/net/dnsfallback"
	_ "scale.ropsoft.cloud/net/netmon"
	_ "scale.ropsoft.cloud/net/netns"
	_ "scale.ropsoft.cloud/net/proxymux"
	_ "scale.ropsoft.cloud/net/socks5"
	_ "scale.ropsoft.cloud/net/tsdial"
	_ "scale.ropsoft.cloud/net/tshttpproxy"
	_ "scale.ropsoft.cloud/net/tstun"
	_ "scale.ropsoft.cloud/paths"
	_ "scale.ropsoft.cloud/safesocket"
	_ "scale.ropsoft.cloud/syncs"
	_ "scale.ropsoft.cloud/tailcfg"
	_ "scale.ropsoft.cloud/tsd"
	_ "scale.ropsoft.cloud/tsweb/varz"
	_ "scale.ropsoft.cloud/types/flagtype"
	_ "scale.ropsoft.cloud/types/key"
	_ "scale.ropsoft.cloud/types/logger"
	_ "scale.ropsoft.cloud/types/logid"
	_ "scale.ropsoft.cloud/util/clientmetric"
	_ "scale.ropsoft.cloud/util/multierr"
	_ "scale.ropsoft.cloud/util/osdiag"
	_ "scale.ropsoft.cloud/util/osshare"
	_ "scale.ropsoft.cloud/util/syspolicy"
	_ "scale.ropsoft.cloud/util/winutil"
	_ "scale.ropsoft.cloud/version"
	_ "scale.ropsoft.cloud/version/distro"
	_ "scale.ropsoft.cloud/wf"
	_ "scale.ropsoft.cloud/wgengine"
	_ "scale.ropsoft.cloud/wgengine/netstack"
	_ "scale.ropsoft.cloud/wgengine/router"
)
