apiVersion: scale.ropsoft.cloud/v1alpha1
kind: ProxyClass
metadata:
  name: prod
spec:
  metrics:
    enable: true
  statefulSet:
    annotations:
      platform-component: infra
    pod:
      labels:
        team: eng
      nodeSelector:
        kubernetes.io/os: "linux"
      imagePullSecrets:
      - name: "foo"
      rspscaleContainer:
        image: "ghcr.io/ropsoft7/rspscale:v1.64"
        imagePullPolicy: IfNotPresent
      rspscaleInitContainer:
        image: "ghcr.io/ropsoft7/rspscale:v1.64"
        imagePullPolicy: IfNotPresent
